services:
  homelab-network:
    build: .
    container_name: homelab-network
    ports:
      - "3301:3301"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgres://homelab_user:homelab_password@postgres:5432/homelab_db
      - PGUSER=homelab_user
      - PGHOST=postgres
      - PGPASSWORD=homelab_password
      - PGDATABASE=homelab_db
      - PGPORT=5432
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: homelab-postgres
    environment:
      - POSTGRES_USER=homelab_user
      - POSTGRES_PASSWORD=homelab_password
      - POSTGRES_DB=homelab_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
